// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.21.7
 * source: cosmos_proto/cosmos.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
export namespace cosmos_proto { }
