// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.21.7
 * source: spidex/oracle/v1/genesis.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_2 from "./params";
import * as dependency_3 from "./coin_symbol";
import * as pb_1 from "google-protobuf";
export namespace pngfi.spidex.oracle.v1 {
    export class GenesisState extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            params?: dependency_2.pngfi.spidex.oracle.v1.Params;
            port_id?: string;
            coinSymbolList?: dependency_3.pngfi.spidex.oracle.v1.CoinSymbol[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [3], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("params" in data && data.params != undefined) {
                    this.params = data.params;
                }
                if ("port_id" in data && data.port_id != undefined) {
                    this.port_id = data.port_id;
                }
                if ("coinSymbolList" in data && data.coinSymbolList != undefined) {
                    this.coinSymbolList = data.coinSymbolList;
                }
            }
        }
        get params() {
            return pb_1.Message.getWrapperField(this, dependency_2.pngfi.spidex.oracle.v1.Params, 1) as dependency_2.pngfi.spidex.oracle.v1.Params;
        }
        set params(value: dependency_2.pngfi.spidex.oracle.v1.Params) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_params() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get port_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set port_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get coinSymbolList() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_3.pngfi.spidex.oracle.v1.CoinSymbol, 3) as dependency_3.pngfi.spidex.oracle.v1.CoinSymbol[];
        }
        set coinSymbolList(value: dependency_3.pngfi.spidex.oracle.v1.CoinSymbol[]) {
            pb_1.Message.setRepeatedWrapperField(this, 3, value);
        }
        static fromObject(data: {
            params?: ReturnType<typeof dependency_2.pngfi.spidex.oracle.v1.Params.prototype.toObject>;
            port_id?: string;
            coinSymbolList?: ReturnType<typeof dependency_3.pngfi.spidex.oracle.v1.CoinSymbol.prototype.toObject>[];
        }): GenesisState {
            const message = new GenesisState({});
            if (data.params != null) {
                message.params = dependency_2.pngfi.spidex.oracle.v1.Params.fromObject(data.params);
            }
            if (data.port_id != null) {
                message.port_id = data.port_id;
            }
            if (data.coinSymbolList != null) {
                message.coinSymbolList = data.coinSymbolList.map(item => dependency_3.pngfi.spidex.oracle.v1.CoinSymbol.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                params?: ReturnType<typeof dependency_2.pngfi.spidex.oracle.v1.Params.prototype.toObject>;
                port_id?: string;
                coinSymbolList?: ReturnType<typeof dependency_3.pngfi.spidex.oracle.v1.CoinSymbol.prototype.toObject>[];
            } = {};
            if (this.params != null) {
                data.params = this.params.toObject();
            }
            if (this.port_id != null) {
                data.port_id = this.port_id;
            }
            if (this.coinSymbolList != null) {
                data.coinSymbolList = this.coinSymbolList.map((item: dependency_3.pngfi.spidex.oracle.v1.CoinSymbol) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_params)
                writer.writeMessage(1, this.params, () => this.params.serialize(writer));
            if (this.port_id.length)
                writer.writeString(2, this.port_id);
            if (this.coinSymbolList.length)
                writer.writeRepeatedMessage(3, this.coinSymbolList, (item: dependency_3.pngfi.spidex.oracle.v1.CoinSymbol) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GenesisState {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GenesisState();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.params, () => message.params = dependency_2.pngfi.spidex.oracle.v1.Params.deserialize(reader));
                        break;
                    case 2:
                        message.port_id = reader.readString();
                        break;
                    case 3:
                        reader.readMessage(message.coinSymbolList, () => pb_1.Message.addToRepeatedWrapperField(message, 3, dependency_3.pngfi.spidex.oracle.v1.CoinSymbol.deserialize(reader), dependency_3.pngfi.spidex.oracle.v1.CoinSymbol));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GenesisState {
            return GenesisState.deserialize(bytes);
        }
    }
}
